# Auto-generated from getdesign.md catalog (62 brands)
# Source: https://getdesign.md
# Generated: 2026-06-19

GETDESIGN_BRANDS = {
    "airbnb": {
        "name": "Airbnb",
        "primary": "#ff385c",
        "secondary": "#ff385c",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#222222",
        "text_secondary": "#6E6E73",
        "border": "#dddddd",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#222222",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#dddddd",
        "hairline_strong": "#dddddd",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "'Airbnb Cereal VF', Circular, sans-serif",
        "font_body": "'Airbnb Cereal VF', Circular, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(255,56,92,0.3)",
        "gradient": "linear-gradient(135deg, #ff385c, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "airtable": {
        "name": "Airtable",
        "primary": "#181d26",
        "secondary": "#181d26",
        "accent": "#2997FF",
        "success": "#006400",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#254fad",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#181d26",
        "text_secondary": "#6E6E73",
        "border": "#dddddd",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#181d26",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#dddddd",
        "hairline_strong": "#dddddd",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Haas Groot Disp, Haas, sans-serif",
        "font_body": "Haas, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(24,29,38,0.3)",
        "gradient": "linear-gradient(135deg, #181d26, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "apple": {
        "name": "Apple",
        "primary": "#0066cc",
        "secondary": "#0071e3",
        "accent": "#2997ff",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#0071e3",
        "bg": "#ffffff",
        "surface": "#fafafc",
        "text": "#1d1d1f",
        "text_secondary": "#cccccc",
        "border": "#e0e0e0",
        "canvas": "#ffffff",
        "canvas_soft": "#f5f5f7",
        "ink": "#1d1d1f",
        "ink_muted": "#cccccc",
        "ink_subtle": "#7a7a7a",
        "hairline": "#e0e0e0",
        "hairline_strong": "#f0f0f0",
        "surface_1": "#fafafc",
        "surface_2": "#fafafc",
        "surface_3": "#f5f5f7",
        "surface_4": "#272729",
        "font_display": "SF Pro Display, system-ui, -apple-system, sans-serif",
        "font_body": "SF Pro Text, system-ui, -apple-system, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,102,204,0.3)",
        "gradient": "linear-gradient(135deg, #0066cc, #2997ff)",
        "dark_bg": "#000000",
        "dark_surface": "#272729",
        "dark_text": "#ffffff",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#2a2a2c",
        "dark_ink": "#ffffff",
        "dark_hairline": "#333333",
        "dark_surface_1": "#272729",
        "dark_surface_2": "#2a2a2c",
        "dark_surface_3": "#252527",
        "dark_surface_4": "#333333",
    },
    "binance": {
        "name": "Binance",
        "primary": "#fcd535",
        "secondary": "#fcd535",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#3b82f6",
        "bg": "#FFFFFF",
        "surface": "#FAFAFC",
        "text": "#181a20",
        "text_secondary": "#6E6E73",
        "border": "#D2D2D7",
        "canvas": "#FFFFFF",
        "canvas_soft": "#F5F5F5",
        "ink": "#181a20",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#D2D2D7",
        "hairline_strong": "#C7C7CC",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "BinanceNova, -apple-system, BlinkMacSystemFont, sans-serif",
        "font_body": "BinanceNova, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(252,213,53,0.3)",
        "gradient": "linear-gradient(135deg, #fcd535, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "bmw": {
        "name": "BMW",
        "primary": "#1c69d4",
        "secondary": "#1c69d4",
        "accent": "#2997FF",
        "success": "#22c55e",
        "warning": "#f59e0b",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#262626",
        "text_secondary": "#6E6E73",
        "border": "#e6e6e6",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#262626",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e6e6e6",
        "hairline_strong": "#e6e6e6",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "'BMW Type Next Latin', sans-serif",
        "font_body": "'BMW Type Next Latin', sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(28,105,212,0.3)",
        "gradient": "linear-gradient(135deg, #1c69d4, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "bmw-m": {
        "name": "BMW-M",
        "primary": "#ffffff",
        "secondary": "#ffffff",
        "accent": "#2997FF",
        "success": "#0fa336",
        "warning": "#f4b400",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#000000",
        "surface": "#FAFAFC",
        "text": "#ffffff",
        "text_secondary": "#6E6E73",
        "border": "#3c3c3c",
        "canvas": "#000000",
        "canvas_soft": "#F5F5F5",
        "ink": "#ffffff",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#3c3c3c",
        "hairline_strong": "#3c3c3c",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "BMWTypeNextLatin, sans-serif",
        "font_body": "BMWTypeNextLatin Light, BMWTypeNextLatin, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(255,255,255,0.3)",
        "gradient": "linear-gradient(135deg, #ffffff, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "bugatti": {
        "name": "Bugatti",
        "primary": "#ffffff",
        "secondary": "#ffffff",
        "accent": "#2997FF",
        "success": "#5fa657",
        "warning": "#d4a017",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#000000",
        "surface": "#FAFAFC",
        "text": "#ffffff",
        "text_secondary": "#6E6E73",
        "border": "#262626",
        "canvas": "#000000",
        "canvas_soft": "#F5F5F5",
        "ink": "#ffffff",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#262626",
        "hairline_strong": "#262626",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Bugatti Display, sans-serif",
        "font_body": "Bugatti Text Regular, serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(255,255,255,0.3)",
        "gradient": "linear-gradient(135deg, #ffffff, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "cal": {
        "name": "Cal.com",
        "primary": "#111111",
        "secondary": "#111111",
        "accent": "#2997FF",
        "success": "#10b981",
        "warning": "#f59e0b",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#111111",
        "text_secondary": "#6E6E73",
        "border": "#e5e7eb",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#111111",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e5e7eb",
        "hairline_strong": "#e5e7eb",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Cal Sans, Inter, sans-serif",
        "font_body": "Inter, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(17,17,17,0.3)",
        "gradient": "linear-gradient(135deg, #111111, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "claude": {
        "name": "Claude",
        "primary": "#cc785c",
        "secondary": "#cc785c",
        "accent": "#2997FF",
        "success": "#5db872",
        "warning": "#d4a017",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#faf9f5",
        "surface": "#FAFAFC",
        "text": "#141413",
        "text_secondary": "#6E6E73",
        "border": "#e6dfd8",
        "canvas": "#faf9f5",
        "canvas_soft": "#F5F5F5",
        "ink": "#141413",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e6dfd8",
        "hairline_strong": "#e6dfd8",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Copernicus, Tiempos Headline, serif",
        "font_body": "StyreneB, Inter, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(204,120,92,0.3)",
        "gradient": "linear-gradient(135deg, #cc785c, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "clay": {
        "name": "Clay",
        "primary": "#0a0a0a",
        "secondary": "#0a0a0a",
        "accent": "#2997FF",
        "success": "#22c55e",
        "warning": "#f59e0b",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#fffaf0",
        "surface": "#FAFAFC",
        "text": "#0a0a0a",
        "text_secondary": "#6E6E73",
        "border": "#e5e5e5",
        "canvas": "#fffaf0",
        "canvas_soft": "#F5F5F5",
        "ink": "#0a0a0a",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e5e5e5",
        "hairline_strong": "#e5e5e5",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Plain Black, Inter, sans-serif",
        "font_body": "Inter, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(10,10,10,0.3)",
        "gradient": "linear-gradient(135deg, #0a0a0a, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "clickhouse": {
        "name": "ClickHouse",
        "primary": "#faff69",
        "secondary": "#faff69",
        "accent": "#2997FF",
        "success": "#22c55e",
        "warning": "#f59e0b",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#0a0a0a",
        "surface": "#FAFAFC",
        "text": "#ffffff",
        "text_secondary": "#6E6E73",
        "border": "#2a2a2a",
        "canvas": "#0a0a0a",
        "canvas_soft": "#F5F5F5",
        "ink": "#ffffff",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#2a2a2a",
        "hairline_strong": "#2a2a2a",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Inter, sans-serif",
        "font_body": "Inter, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(250,255,105,0.3)",
        "gradient": "linear-gradient(135deg, #faff69, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "cohere": {
        "name": "Cohere",
        "primary": "#17171c",
        "secondary": "#17171c",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#212121",
        "text_secondary": "#616161",
        "border": "#d9d9dd",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#212121",
        "ink_muted": "#616161",
        "ink_subtle": "#86868B",
        "hairline": "#d9d9dd",
        "hairline_strong": "#d9d9dd",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "CohereText",
        "font_body": "Unica77 Cohere Web",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(23,23,28,0.3)",
        "gradient": "linear-gradient(135deg, #17171c, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "coinbase": {
        "name": "Coinbase",
        "primary": "#0052ff",
        "secondary": "#0052ff",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#0a0b0d",
        "text_secondary": "#6E6E73",
        "border": "#dee1e6",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#0a0b0d",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#dee1e6",
        "hairline_strong": "#dee1e6",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "'Coinbase Display', sans-serif",
        "font_body": "'Coinbase Sans', sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,82,255,0.3)",
        "gradient": "linear-gradient(135deg, #0052ff, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "composio": {
        "name": "Composio",
        "primary": "#0007cd",
        "secondary": "#0007cd",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#0f0f0f",
        "surface": "#FAFAFC",
        "text": "#ffffff",
        "text_secondary": "#6E6E73",
        "border": "#222222",
        "canvas": "#0f0f0f",
        "canvas_soft": "#F5F5F5",
        "ink": "#ffffff",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#222222",
        "hairline_strong": "#222222",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "'abcDiatype', ui-sans-serif, system-ui, sans-serif",
        "font_body": "'abcDiatype', ui-sans-serif, system-ui, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,7,205,0.3)",
        "gradient": "linear-gradient(135deg, #0007cd, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "cursor": {
        "name": "Cursor",
        "primary": "#f54e00",
        "secondary": "#f54e00",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#f7f7f4",
        "surface": "#FAFAFC",
        "text": "#26251e",
        "text_secondary": "#6E6E73",
        "border": "#e6e5e0",
        "canvas": "#f7f7f4",
        "canvas_soft": "#F5F5F5",
        "ink": "#26251e",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e6e5e0",
        "hairline_strong": "#e6e5e0",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "'CursorGothic', sans-serif",
        "font_body": "'CursorGothic', sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(245,78,0,0.3)",
        "gradient": "linear-gradient(135deg, #f54e00, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "dell-1996": {
        "name": "Dell 1996",
        "primary": "#e91d2a",
        "secondary": "#e91d2a",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#000000",
        "text_secondary": "#6E6E73",
        "border": "#D2D2D7",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#000000",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#D2D2D7",
        "hairline_strong": "#C7C7CC",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "SF Pro Display, system-ui, -apple-system, sans-serif",
        "font_body": "Times New Roman",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(233,29,42,0.3)",
        "gradient": "linear-gradient(135deg, #e91d2a, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "discord": {
        "name": "Discord",
        "primary": "#5865f2",
        "secondary": "#5865f2",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#0a0d3a",
        "surface": "#FAFAFC",
        "text": "#ffffff",
        "text_secondary": "#6E6E73",
        "border": "#23272a",
        "canvas": "#0a0d3a",
        "canvas_soft": "#F5F5F5",
        "ink": "#ffffff",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#23272a",
        "hairline_strong": "#23272a",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "ABC Ginto Nord",
        "font_body": "ggsans",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(88,101,242,0.3)",
        "gradient": "linear-gradient(135deg, #5865f2, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "expo": {
        "name": "Expo",
        "primary": "#000000",
        "secondary": "#000000",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#171717",
        "text_secondary": "#6E6E73",
        "border": "#f0f0f3",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#171717",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#f0f0f3",
        "hairline_strong": "#f0f0f3",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "'Inter', sans-serif",
        "font_body": "'Inter', sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,0,0,0.3)",
        "gradient": "linear-gradient(135deg, #000000, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "ferrari": {
        "name": "Ferrari",
        "primary": "#da291c",
        "secondary": "#da291c",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#181818",
        "surface": "#FAFAFC",
        "text": "#ffffff",
        "text_secondary": "#6E6E73",
        "border": "#303030",
        "canvas": "#181818",
        "canvas_soft": "#F5F5F5",
        "ink": "#ffffff",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#303030",
        "hairline_strong": "#303030",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "'FerrariSans', sans-serif",
        "font_body": "'FerrariSans', sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(218,41,28,0.3)",
        "gradient": "linear-gradient(135deg, #da291c, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "figma": {
        "name": "Figma",
        "primary": "#000000",
        "secondary": "#000000",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#000000",
        "text_secondary": "#6E6E73",
        "border": "#e6e6e6",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#000000",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e6e6e6",
        "hairline_strong": "#e6e6e6",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "figmaSans",
        "font_body": "figmaSans",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,0,0,0.3)",
        "gradient": "linear-gradient(135deg, #000000, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "framer": {
        "name": "Framer",
        "primary": "#ffffff",
        "secondary": "#ffffff",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#090909",
        "surface": "#FAFAFC",
        "text": "#ffffff",
        "text_secondary": "#6E6E73",
        "border": "#262626",
        "canvas": "#090909",
        "canvas_soft": "#F5F5F5",
        "ink": "#ffffff",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#262626",
        "hairline_strong": "#262626",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "GT Walsheim Medium",
        "font_body": "Inter Variable",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(255,255,255,0.3)",
        "gradient": "linear-gradient(135deg, #ffffff, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "hashicorp": {
        "name": "HashiCorp",
        "primary": "#000000",
        "secondary": "#000000",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#000000",
        "surface": "#FAFAFC",
        "text": "#ffffff",
        "text_secondary": "#6E6E73",
        "border": "#3b3d45",
        "canvas": "#000000",
        "canvas_soft": "#F5F5F5",
        "ink": "#ffffff",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#3b3d45",
        "hairline_strong": "#3b3d45",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "hashicorpSans",
        "font_body": "hashicorpSans",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,0,0,0.3)",
        "gradient": "linear-gradient(135deg, #000000, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "hp": {
        "name": "HP",
        "primary": "#024ad8",
        "secondary": "#024ad8",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#1a1a1a",
        "text_secondary": "#6E6E73",
        "border": "#e8e8e8",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#1a1a1a",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e8e8e8",
        "hairline_strong": "#e8e8e8",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Forma DJR Micro",
        "font_body": "Forma DJR Micro",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(2,74,216,0.3)",
        "gradient": "linear-gradient(135deg, #024ad8, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "ibm": {
        "name": "IBM",
        "primary": "#0f62fe",
        "secondary": "#0f62fe",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#161616",
        "text_secondary": "#6E6E73",
        "border": "#e0e0e0",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#161616",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e0e0e0",
        "hairline_strong": "#e0e0e0",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "IBM Plex Sans",
        "font_body": "IBM Plex Sans",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(15,98,254,0.3)",
        "gradient": "linear-gradient(135deg, #0f62fe, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "intercom": {
        "name": "Intercom",
        "primary": "#111111",
        "secondary": "#111111",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#f5f1ec",
        "surface": "#FAFAFC",
        "text": "#111111",
        "text_secondary": "#6E6E73",
        "border": "#d3cec6",
        "canvas": "#f5f1ec",
        "canvas_soft": "#F5F5F5",
        "ink": "#111111",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#d3cec6",
        "hairline_strong": "#d3cec6",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Saans",
        "font_body": "Saans",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(17,17,17,0.3)",
        "gradient": "linear-gradient(135deg, #111111, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "linear": {
        "name": "Linear",
        "primary": "#5e6ad2",
        "secondary": "#5e69d1",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#5e69d1",
        "bg": "#010102",
        "surface": "#FAFAFC",
        "text": "#f7f8f8",
        "text_secondary": "#6E6E73",
        "border": "#23252a",
        "canvas": "#010102",
        "canvas_soft": "#F5F5F5",
        "ink": "#f7f8f8",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#23252a",
        "hairline_strong": "#23252a",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Linear Display",
        "font_body": "Linear Text",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(94,106,210,0.3)",
        "gradient": "linear-gradient(135deg, #5e6ad2, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "meta": {
        "name": "Meta",
        "primary": "#0064e0",
        "secondary": "#0064e0",
        "accent": "#2997FF",
        "success": "#31a24c",
        "warning": "#f7b928",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#1c1e21",
        "text_secondary": "#6E6E73",
        "border": "#ced0d4",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#1c1e21",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#ced0d4",
        "hairline_strong": "#ced0d4",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Optimistic VF",
        "font_body": "Optimistic VF",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,100,224,0.3)",
        "gradient": "linear-gradient(135deg, #0064e0, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "minimax": {
        "name": "MiniMax",
        "primary": "#0a0a0a",
        "secondary": "#0a0a0a",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#0a0a0a",
        "text_secondary": "#6E6E73",
        "border": "#e5e7eb",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#0a0a0a",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e5e7eb",
        "hairline_strong": "#e5e7eb",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "DM Sans",
        "font_body": "DM Sans",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(10,10,10,0.3)",
        "gradient": "linear-gradient(135deg, #0a0a0a, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "mintlify": {
        "name": "Mintlify",
        "primary": "#0a0a0a",
        "secondary": "#0a0a0a",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#0a0a0a",
        "text_secondary": "#6E6E73",
        "border": "#e5e5e5",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#0a0a0a",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e5e5e5",
        "hairline_strong": "#e5e5e5",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Inter",
        "font_body": "Inter",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(10,10,10,0.3)",
        "gradient": "linear-gradient(135deg, #0a0a0a, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "miro": {
        "name": "Miro",
        "primary": "#1c1c1e",
        "secondary": "#1c1c1e",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#1c1c1e",
        "text_secondary": "#6E6E73",
        "border": "#e0e2e8",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#1c1c1e",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e0e2e8",
        "hairline_strong": "#e0e2e8",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Roobert PRO",
        "font_body": "Roobert PRO",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(28,28,30,0.3)",
        "gradient": "linear-gradient(135deg, #1c1c1e, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "mistral": {
        "name": "Mistral-AI",
        "primary": "#fa520f",
        "secondary": "#fa520f",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#1f1f1f",
        "text_secondary": "#6E6E73",
        "border": "#e5e5e5",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#1f1f1f",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e5e5e5",
        "hairline_strong": "#e5e5e5",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "PP Editorial Old",
        "font_body": "Inter",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(250,82,15,0.3)",
        "gradient": "linear-gradient(135deg, #fa520f, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "mongodb": {
        "name": "MongoDB",
        "primary": "#00ed64",
        "secondary": "#00ed64",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#001e2b",
        "text_secondary": "#6E6E73",
        "border": "#e1e5e8",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#001e2b",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e1e5e8",
        "hairline_strong": "#e1e5e8",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Euclid Circular A",
        "font_body": "Euclid Circular A",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,237,100,0.3)",
        "gradient": "linear-gradient(135deg, #00ed64, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "nike": {
        "name": "Nike",
        "primary": "#111111",
        "secondary": "#111111",
        "accent": "#2997FF",
        "success": "#007d48",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#1151ff",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#111111",
        "text_secondary": "#6E6E73",
        "border": "#cacacb",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#111111",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#cacacb",
        "hairline_strong": "#cacacb",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Helvetica Now Display Medium",
        "font_body": "Helvetica Now Text",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(17,17,17,0.3)",
        "gradient": "linear-gradient(135deg, #111111, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "nintendo-2001": {
        "name": "Nintendo.com (2001)",
        "primary": "#e60012",
        "secondary": "#e60012",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#7a8aba",
        "surface": "#FAFAFC",
        "text": "#21242e",
        "text_secondary": "#6E6E73",
        "border": "#5a5f8c",
        "canvas": "#7a8aba",
        "canvas_soft": "#F5F5F5",
        "ink": "#21242e",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#5a5f8c",
        "hairline_strong": "#5a5f8c",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "SF Pro Display, system-ui, -apple-system, sans-serif",
        "font_body": "Arial",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(230,0,18,0.3)",
        "gradient": "linear-gradient(135deg, #e60012, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "notion": {
        "name": "Notion",
        "primary": "#0075de",
        "secondary": "#0075de",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#000000",
        "text_secondary": "#6E6E73",
        "border": "#e6e6e6",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#000000",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e6e6e6",
        "hairline_strong": "#e6e6e6",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "SF Pro Display, system-ui, -apple-system, sans-serif",
        "font_body": "NotionInter",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,117,222,0.3)",
        "gradient": "linear-gradient(135deg, #0075de, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "nvidia": {
        "name": "NVIDIA",
        "primary": "#76b900",
        "secondary": "#76b900",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#df6500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#000000",
        "text_secondary": "#6E6E73",
        "border": "#cccccc",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#000000",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#cccccc",
        "hairline_strong": "#cccccc",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "NVIDIA-EMEA",
        "font_body": "NVIDIA-EMEA",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(118,185,0,0.3)",
        "gradient": "linear-gradient(135deg, #76b900, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "ollama": {
        "name": "Ollama",
        "primary": "#000000",
        "secondary": "#000000",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#000000",
        "text_secondary": "#6E6E73",
        "border": "#e5e5e5",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#000000",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e5e5e5",
        "hairline_strong": "#e5e5e5",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "SF Pro Rounded",
        "font_body": "ui-sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,0,0,0.3)",
        "gradient": "linear-gradient(135deg, #000000, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "opencode": {
        "name": "OpenCode",
        "primary": "#201d1d",
        "secondary": "#201d1d",
        "accent": "#007aff",
        "success": "#30d158",
        "warning": "#ff9f0a",
        "danger": "#ff3b30",
        "info": "#007AFF",
        "bg": "#fdfcfc",
        "surface": "#FAFAFC",
        "text": "#201d1d",
        "text_secondary": "#6E6E73",
        "border": "rgba(15,0,0,0.12)",
        "canvas": "#fdfcfc",
        "canvas_soft": "#F5F5F5",
        "ink": "#201d1d",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "rgba(15,0,0,0.12)",
        "hairline_strong": "rgba(15,0,0,0.12)",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Berkeley Mono",
        "font_body": "Berkeley Mono",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(32,29,29,0.3)",
        "gradient": "linear-gradient(135deg, #201d1d, #007aff)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "pinterest": {
        "name": "Pinterest",
        "primary": "#e60023",
        "secondary": "#e60023",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#000000",
        "text_secondary": "#6E6E73",
        "border": "#dadad3",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#000000",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#dadad3",
        "hairline_strong": "#dadad3",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Pin Sans",
        "font_body": "Pin Sans",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(230,0,35,0.3)",
        "gradient": "linear-gradient(135deg, #e60023, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "playstation": {
        "name": "PlayStation",
        "primary": "#0070d1",
        "secondary": "#0070d1",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#c81b3a",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#FFFFFF",
        "surface": "#FAFAFC",
        "text": "#000000",
        "text_secondary": "#6E6E73",
        "border": "#D2D2D7",
        "canvas": "#FFFFFF",
        "canvas_soft": "#F5F5F5",
        "ink": "#000000",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#D2D2D7",
        "hairline_strong": "#C7C7CC",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "PlayStation SST",
        "font_body": "PlayStation SST",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,112,209,0.3)",
        "gradient": "linear-gradient(135deg, #0070d1, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "posthog": {
        "name": "PostHog",
        "primary": "#f7a501",
        "secondary": "#f7a501",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#eeefe9",
        "surface": "#FAFAFC",
        "text": "#23251d",
        "text_secondary": "#6E6E73",
        "border": "#bfc1b7",
        "canvas": "#eeefe9",
        "canvas_soft": "#F5F5F5",
        "ink": "#23251d",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#bfc1b7",
        "hairline_strong": "#bfc1b7",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "IBM Plex Sans Variable",
        "font_body": "IBM Plex Sans Variable",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(247,165,1,0.3)",
        "gradient": "linear-gradient(135deg, #f7a501, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "renault": {
        "name": "Renault",
        "primary": "#ffed00",
        "secondary": "#ffed00",
        "accent": "#2997FF",
        "success": "#8dc572",
        "warning": "#f0ad4e",
        "danger": "#FF3B30",
        "info": "#337ab7",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#000000",
        "text_secondary": "#6E6E73",
        "border": "#f2f2f2",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#000000",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#f2f2f2",
        "hairline_strong": "#f2f2f2",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "NouvelR",
        "font_body": "NouvelR",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(255,237,0,0.3)",
        "gradient": "linear-gradient(135deg, #ffed00, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "replicate": {
        "name": "Replicate",
        "primary": "#ea2804",
        "secondary": "#ea2804",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#f9f7f3",
        "surface": "#FAFAFC",
        "text": "#202020",
        "text_secondary": "#6E6E73",
        "border": "rgba(32,32,32,0.12)",
        "canvas": "#f9f7f3",
        "canvas_soft": "#F5F5F5",
        "ink": "#202020",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "rgba(32,32,32,0.12)",
        "hairline_strong": "rgba(32,32,32,0.12)",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "rb-freigeist-neue",
        "font_body": "basier-square",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(234,40,4,0.3)",
        "gradient": "linear-gradient(135deg, #ea2804, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "resend": {
        "name": "Resend",
        "primary": "#fcfdff",
        "secondary": "#fcfdff",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#000000",
        "surface": "#FAFAFC",
        "text": "#fcfdff",
        "text_secondary": "#6E6E73",
        "border": "rgba(255,255,255,0.06)",
        "canvas": "#000000",
        "canvas_soft": "#F5F5F5",
        "ink": "#fcfdff",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "rgba(255,255,255,0.06)",
        "hairline_strong": "rgba(255,255,255,0.04)",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "ABC Favorit",
        "font_body": "Inter",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(252,253,255,0.3)",
        "gradient": "linear-gradient(135deg, #fcfdff, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "revolut": {
        "name": "Revolut",
        "primary": "#494fdf",
        "secondary": "#494fdf",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#FFFFFF",
        "surface": "#FAFAFC",
        "text": "#191c1f",
        "text_secondary": "#6E6E73",
        "border": "rgba(255,255,255,0.06)",
        "canvas": "#FFFFFF",
        "canvas_soft": "#F5F5F5",
        "ink": "#191c1f",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "rgba(255,255,255,0.06)",
        "hairline_strong": "rgba(255,255,255,0.06)",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Aeonik Pro",
        "font_body": "Inter",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(73,79,223,0.3)",
        "gradient": "linear-gradient(135deg, #494fdf, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "sentry": {
        "name": "Sentri",
        "primary": "#150f23",
        "secondary": "#150f23",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#FFFFFF",
        "surface": "#FAFAFC",
        "text": "#1f1633",
        "text_secondary": "#6E6E73",
        "border": "#D2D2D7",
        "canvas": "#FFFFFF",
        "canvas_soft": "#F5F5F5",
        "ink": "#1f1633",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#D2D2D7",
        "hairline_strong": "#C7C7CC",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Rubik, -apple-system, system-ui, sans-serif",
        "font_body": "Rubik, -apple-system, system-ui, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(21,15,35,0.3)",
        "gradient": "linear-gradient(135deg, #150f23, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "shopify": {
        "name": "Shopifi",
        "primary": "#000000",
        "secondary": "#000000",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#FFFFFF",
        "surface": "#FAFAFC",
        "text": "#000000",
        "text_secondary": "#6E6E73",
        "border": "#D2D2D7",
        "canvas": "#FFFFFF",
        "canvas_soft": "#F5F5F5",
        "ink": "#000000",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#D2D2D7",
        "hairline_strong": "#C7C7CC",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "NeueHaasGrotesk Display, Helvetica, Arial, sans-serif",
        "font_body": "Inter Variable, Inter, Helvetica, Arial, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,0,0,0.3)",
        "gradient": "linear-gradient(135deg, #000000, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "slack": {
        "name": "Slacc",
        "primary": "#4a154b",
        "secondary": "#4a154b",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#1d1d1d",
        "text_secondary": "#6E6E73",
        "border": "#e6e6e6",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#1d1d1d",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e6e6e6",
        "hairline_strong": "#e6e6e6",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Salesforce-Avant-Garde, system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
        "font_body": "Salesforce-Sans, system-ui, -apple-system, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(74,21,75,0.3)",
        "gradient": "linear-gradient(135deg, #4a154b, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "spacex": {
        "name": "Spacex",
        "primary": "#000000",
        "secondary": "#000000",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#FFFFFF",
        "surface": "#FAFAFC",
        "text": "#000000",
        "text_secondary": "#6E6E73",
        "border": "#D2D2D7",
        "canvas": "#FFFFFF",
        "canvas_soft": "#F5F5F5",
        "ink": "#000000",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#D2D2D7",
        "hairline_strong": "#C7C7CC",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "D-DIN-Bold, Arial Narrow, Arial, Verdana, sans-serif",
        "font_body": "D-DIN, Arial, Verdana, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,0,0,0.3)",
        "gradient": "linear-gradient(135deg, #000000, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "stripe": {
        "name": "Stripi",
        "primary": "#533afd",
        "secondary": "#533afd",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#0d253d",
        "text_secondary": "#6E6E73",
        "border": "#e3e8ee",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#0d253d",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e3e8ee",
        "hairline_strong": "#e3e8ee",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "sohne-var, 'SF Pro Display', system-ui, -apple-system, sans-serif",
        "font_body": "sohne-var, 'SF Pro Display', system-ui, -apple-system, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(83,58,253,0.3)",
        "gradient": "linear-gradient(135deg, #533afd, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "superhuman": {
        "name": "Superhumon",
        "primary": "#1b1938",
        "secondary": "#1b1938",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#292827",
        "text_secondary": "#6E6E73",
        "border": "#e8e4dd",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#292827",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e8e4dd",
        "hairline_strong": "#e8e4dd",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "'Super Sans VF', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
        "font_body": "'Super Sans VF', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(27,25,56,0.3)",
        "gradient": "linear-gradient(135deg, #1b1938, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "together": {
        "name": "Together-AI",
        "primary": "#000000",
        "secondary": "#000000",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#000000",
        "text_secondary": "#6E6E73",
        "border": "#959494",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#000000",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#959494",
        "hairline_strong": "#959494",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "The Future, Inter, Helvetica Neue, Arial, sans-serif",
        "font_body": "The Future, Inter, Helvetica Neue, Arial, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,0,0,0.3)",
        "gradient": "linear-gradient(135deg, #000000, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "uber": {
        "name": "Uber",
        "primary": "#000000",
        "secondary": "#000000",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#000000",
        "text_secondary": "#6E6E73",
        "border": "#D2D2D7",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#000000",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#D2D2D7",
        "hairline_strong": "#C7C7CC",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "UberMove, UberMoveText, system-ui, Helvetica Neue, Arial, sans-serif",
        "font_body": "UberMoveText, system-ui, Helvetica Neue, Arial, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,0,0,0.3)",
        "gradient": "linear-gradient(135deg, #000000, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "vercel": {
        "name": "Vercel",
        "primary": "#171717",
        "secondary": "#171717",
        "accent": "#2997FF",
        "success": "#0070f3",
        "warning": "#f5a623",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#171717",
        "text_secondary": "#6E6E73",
        "border": "#ebebeb",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#171717",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#ebebeb",
        "hairline_strong": "#ebebeb",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Geist, Inter, system-ui, -apple-system, sans-serif",
        "font_body": "Geist, Inter, system-ui, -apple-system, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(23,23,23,0.3)",
        "gradient": "linear-gradient(135deg, #171717, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "vodafone": {
        "name": "Vodafone",
        "primary": "#e60000",
        "secondary": "#e60000",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#25282b",
        "text_secondary": "#6E6E73",
        "border": "#D2D2D7",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#25282b",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#D2D2D7",
        "hairline_strong": "#C7C7CC",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Vodafone, Vodafone Rg, Helvetica Neue, Arial, sans-serif",
        "font_body": "Vodafone, Vodafone Rg, Helvetica Neue, Arial, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(230,0,0,0.3)",
        "gradient": "linear-gradient(135deg, #e60000, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "voltagent": {
        "name": "Voltagent",
        "primary": "#00d992",
        "secondary": "#00d992",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#101010",
        "surface": "#FAFAFC",
        "text": "#f2f2f2",
        "text_secondary": "#6E6E73",
        "border": "#3d3a39",
        "canvas": "#101010",
        "canvas_soft": "#F5F5F5",
        "ink": "#f2f2f2",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#3d3a39",
        "hairline_strong": "#3d3a39",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Inter, system-ui, -apple-system, Segoe UI, Roboto, sans-serif",
        "font_body": "Inter, system-ui, -apple-system, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,217,146,0.3)",
        "gradient": "linear-gradient(135deg, #00d992, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "warp": {
        "name": "Warp",
        "primary": "#f7f5f0",
        "secondary": "#f7f5f0",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#2b2622",
        "surface": "#FAFAFC",
        "text": "#f7f5f0",
        "text_secondary": "#6E6E73",
        "border": "#3f3a36",
        "canvas": "#2b2622",
        "canvas_soft": "#F5F5F5",
        "ink": "#f7f5f0",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#3f3a36",
        "hairline_strong": "#3f3a36",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Inter, system-ui, -apple-system, sans-serif",
        "font_body": "Inter, system-ui, -apple-system, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(247,245,240,0.3)",
        "gradient": "linear-gradient(135deg, #f7f5f0, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "webflow": {
        "name": "Webflow",
        "primary": "#080808",
        "secondary": "#080808",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#080808",
        "text_secondary": "#6E6E73",
        "border": "#d8d8d8",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#080808",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#d8d8d8",
        "hairline_strong": "#d8d8d8",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "WF Visual Sans Variable, Inter, system-ui, sans-serif",
        "font_body": "WF Visual Sans Variable, Inter, system-ui, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(8,8,8,0.3)",
        "gradient": "linear-gradient(135deg, #080808, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "wired": {
        "name": "Wired",
        "primary": "#000000",
        "secondary": "#000000",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#000000",
        "text_secondary": "#6E6E73",
        "border": "#e0e0e0",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#000000",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#e0e0e0",
        "hairline_strong": "#e0e0e0",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "WiredDisplay, Times New Roman, Georgia, serif",
        "font_body": "Apercu, Helvetica Neue, Helvetica, Arial, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(0,0,0,0.3)",
        "gradient": "linear-gradient(135deg, #000000, #2997FF",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "wise": {
        "name": "Wise",
        "primary": "#9fe870",
        "secondary": "#9fe870",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#ffd11a",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#ffffff",
        "surface": "#FAFAFC",
        "text": "#0e0f0c",
        "text_secondary": "#6E6E73",
        "border": "#D2D2D7",
        "canvas": "#ffffff",
        "canvas_soft": "#F5F5F5",
        "ink": "#0e0f0c",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#D2D2D7",
        "hairline_strong": "#C7C7CC",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Wise Sans, Inter, system-ui, sans-serif",
        "font_body": "Inter, system-ui, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(159,232,112,0.3)",
        "gradient": "linear-gradient(135deg, #9fe870, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "x-ai": {
        "name": "xAI",
        "primary": "#ffffff",
        "secondary": "#ffffff",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#0a0a0a",
        "surface": "#FAFAFC",
        "text": "#ffffff",
        "text_secondary": "#6E6E73",
        "border": "#212327",
        "canvas": "#0a0a0a",
        "canvas_soft": "#F5F5F5",
        "ink": "#ffffff",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#212327",
        "hairline_strong": "#212327",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "universalSans, Inter, system-ui, sans-serif",
        "font_body": "universalSans, Inter, system-ui, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(255,255,255,0.3)",
        "gradient": "linear-gradient(135deg, #ffffff, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },
    "zapier": {
        "name": "Zapier",
        "primary": "#ff4f00",
        "secondary": "#ff4f00",
        "accent": "#2997FF",
        "success": "#34C759",
        "warning": "#FF9500",
        "danger": "#FF3B30",
        "info": "#007AFF",
        "bg": "#fffefb",
        "surface": "#FAFAFC",
        "text": "#201515",
        "text_secondary": "#6E6E73",
        "border": "#D2D2D7",
        "canvas": "#fffefb",
        "canvas_soft": "#F5F5F5",
        "ink": "#201515",
        "ink_muted": "#6E6E73",
        "ink_subtle": "#86868B",
        "hairline": "#D2D2D7",
        "hairline_strong": "#C7C7CC",
        "surface_1": "#FFFFFF",
        "surface_2": "#FAFAFC",
        "surface_3": "#F5F5F7",
        "surface_4": "#E8E8ED",
        "font_display": "Degular Display, Inter, system-ui, sans-serif",
        "font_body": "Inter, system-ui, sans-serif",
        "font_mono": "'SF Mono', 'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(255,79,0,0.3)",
        "gradient": "linear-gradient(135deg, #ff4f00, #2997FF)",
        "dark_bg": "#000000",
        "dark_surface": "#1D1D1F",
        "dark_text": "#F5F5F7",
        "dark_border": "#333333",
        "dark_canvas": "#000000",
        "dark_canvas_soft": "#1D1D1F",
        "dark_ink": "#F5F5F7",
        "dark_hairline": "#333333",
        "dark_surface_1": "#1D1D1F",
        "dark_surface_2": "#2D2D2F",
        "dark_surface_3": "#3A3A3C",
        "dark_surface_4": "#48484A",
    },

    "stripe-stitch": {
        "name": "Stripe (Stitch Polished)",
        "primary": "#635BFF",
        "secondary": "#493EE5",
        "accent": "#00D4FF",
        "success": "#22C55E",
        "warning": "#F59E0B",
        "danger": "#EF4444",
        "info": "#3B82F6",
        "bg": "#FCF8FF",
        "surface": "#FCF8FF",
        "text": "#1B1B24",
        "text_secondary": "#464555",
        "border": "#C7C4D8",
        "canvas": "#FCF8FF",
        "canvas_soft": "#F5F2FF",
        "ink": "#1B1B24",
        "ink_muted": "#464555",
        "ink_subtle": "#777587",
        "hairline": "#C7C4D8",
        "hairline_strong": "#777587",
        "surface_1": "#FFFFFF",
        "surface_2": "#FCF8FF",
        "surface_3": "#F0ECFA",
        "surface_4": "#E4E1EE",
        "font_display": "'Hanken Grotesk', 'Inter', system-ui, sans-serif",
        "font_body": "'Inter', system-ui, -apple-system, sans-serif",
        "font_mono": "'JetBrains Mono', 'Fira Code', monospace",
        "glow_rgba": "rgba(99,91,255,0.3)",
        "gradient": "linear-gradient(135deg, #635BFF, #00D4FF)",
        "dark_bg": "#1B1B24",
        "dark_surface": "#302F39",
        "dark_text": "#F3EFFD",
        "dark_border": "#777587",
        "dark_canvas": "#1B1B24",
        "dark_canvas_soft": "#1B1B24",
        "dark_ink": "#F3EFFD",
        "dark_hairline": "#777587",
        "dark_surface_1": "#302F39",
        "dark_surface_2": "#1B1B24",
        "dark_surface_3": "#302F39",
        "dark_surface_4": "#464555"
    }

}
